{
    'name': 'Builder',
    'version': '19.0.1.3',
    'category': 'Construction',
    'depends': [
        'crm_enterprise',
        'documents',
        'helpdesk',
        'industry_fsm_stock',
        'knowledge',
        'purchase_stock',
        'sale_crm',
        'sale_margin',
        'sale_project_forecast',
        'sale_timesheet_enterprise',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_ui_view.xml',
    ],
    'license': 'OEEL-1',
    'author': 'Odoo S.A.',
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=construction",
    'website': "https://www.odoo.com/industries/construction",
}
